### PR TITLE
Updated 2020 data

### PR DESCRIPTION
**Pull request by abrieff**
Based on email from Erica, update underlying 2020 acs data. Main check here is verifying 
1. The script still works
2. The data is correctly for 2020, not 2010

### CODE REVIEW

**Comment by SashaWeinstein** [comment]
I ran
```
python3 -m pipelines.acs_2020_manual_update -y 2020 -g 2010_to_2020
```
and got an output that doesn't look quite right? `pop_1` has c=0 for citywide and all boroughs. census_geoid is always `NaN`. Am I running the wrong thing from the command line? If it's not an issue with the args passed I'm happy to help debug

**Comment by abrieff** [comment]
I think that's the right args - i honestly hadn't finished running it, I figured there wouldn't be an issue since nothing was changing.

**Comment by abrieff** [comment]
So I think census_geoid being always null is actually expected behavior -the column itself is only included to keep the shape of the csv the same. I'm not sure about the 0 for pop_1 citywide - that hasn't changed from previous runs of this script so it either represents a persistent bug or also expected behavior coming from the input script

**Comment by SashaWeinstein** [comment]
Ok great. Looking at the source data, I think that "E" is estimate and it looks right. I forgot what each letter stood for

**Review by SashaWeinstein — APPROVED** [review]
Ran on my machine and the output looks good

**Pull request merged**
