### PR TITLE
updated 2020 data

### PR DESCRIPTION
**Pull request by abrieff**
Update 2020 data with latest data from Erica (8/1/2022 1:50 PM)

### CODE REVIEW

**Comment by abrieff** [comment]
lol meant aug 1 2020 - just wanted to save the date of the update for posterity. I wouldn't spend too much time on it, just swapping out the file.

**Comment by SashaWeinstein** [comment]
lol andrew my dude what year is it

**Review by SashaWeinstein — APPROVED** [review]
Ran on my machine and output looks good to me

**Comment by abrieff** [comment]
yikes february 2020 - i think my brain stopped pre-covid

**Comment by SashaWeinstein** [comment]
do you mean post-covid

**Comment by abrieff** [comment]
in my defense, the actual file is from 2020 so it didn't come from nowhere haha

**Comment by abrieff** [comment]
If we're being honest, it probably never worked in the first place

**Pull request merged**
